name: Cloud functions con terraform y github actions
on:
  push:
    branches: [ main ]
env:
  PROJECT: mkdevyoutube

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: mkdevyoutube
          service_account_key: ${{ secrets.GCP_SA }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Plan
        id: init
        run: |
          terraform init
          terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    needs: build
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: mkdevyoutube
          service_account_key: ${{ secrets.GCP_SA }}
          export_default_credentials: true
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Plan
        id: init
        run: |
          terraform init

      - name: 
        run: |
          curl $(terraform output -raw url| sed 's/ /\n/g'|grep ^https|grep Mkdev$) 2> /dev/null

